### ISSUE TITLE
System.InvalidOperationException: 'ValueFactory attempted to access the Value property of this instance.'

### ISSUE THREAD

**Issue by MaryadaPurshottam** [AutoMapper/AutoMapper.Collection.EFCore#13]
I just added Automapper.Collection.EFCore vs 0.1.0 to my aspnet core project. 

I'm initializing it like this in my startup class

            services.AddAutoMapper((cfg)=> 
            {
                cfg.AddCollectionMappers();
                cfg.UseEntityFrameworkCoreModel<MyDbContext>(services);
            });

but when I run the project i get this error 
**"ValueFactory attempted to access the Value property of this instance."**

**Comment by Tasteful** [comment]
Try to use the AddAutoMapper-overrided registration like

services.AddAutoMapper((cfg, serviceProvider)=> 
        {
            cfg.AddCollectionMappers();
            cfg.UseEntityFrameworkCoreModel<MyDbContext>(serviceProvider);
        });

**Comment by MaryadaPurshottam** [comment]
Tasteful, I tried that but same error: 

            services.AddAutoMapper((serviceProvider, cfg)=> 
            {
                cfg.AddCollectionMappers();
                cfg.UseEntityFrameworkCoreModel<IwasDbContext>(serviceProvider);
            });

**Comment by Tasteful** [comment]
Please, can you create an gist or a runnable example that demonstrate the error?

**Comment by MaryadaPurshottam** [comment]
See attached demo. Thanks!
[DemoAutomapperCollectionEfCore.zip](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/files/2872409/DemoAutomapperCollectionEfCore.zip)

**Comment by Tasteful** [comment]
The exception is from a circular reference in the mapping that not `AutoMapper.Execution.TypeMapPlanBuilder` (in AM) will handle.

I have separated the test that will reproduce the error and it is a combination of how AM.Collection will check and create `Expressions` where the `Expression` is trying to find the real type. Exception have nothing to do with the AM.Collection.EFCore. The database object models often have references to both child and parent direction and that will cause the exception.

```
[2019-02-17 15:10:25 Error] [xUnit.net 00:00:01.0766059]     AutoMapper.Collection.NotExistingTests.Should_not_throw_exception_for_nonexisting_types [FAIL]
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0774607]       System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0782044]       Stack Trace:
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0788978]            at System.Lazy`1.CreateValue()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0789705]            at System.Lazy`1.LazyInitValue()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0790054]            at System.Lazy`1.get_Value()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0790394]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0790709]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0791232]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveTypeMap|17_5(TypePair types)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0791838]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveMemberTypeMap|17_4(IMemberMap memberMap)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0792289]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(IMemberMap pm)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0792624]            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0792929]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0793235]            at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0793492]            at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0793884]            at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0794398]            at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0794757]            at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0795150]            at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0795523]            at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0795916]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0796236]            at AutoMapper.MapperConfiguration.ResolveTypeMap(Type sourceType, Type destinationType)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0796808]         Automapper.Collection\src\AutoMapper.Collection\EquivalencyExpression\EquivalentExpressions.cs(63,0): at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0797351]         Automapper.Collection\src\AutoMapper.Collection\Mappers\EquivalentExpressionAddRemoveCollectionMapper.cs(76,0): at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0797671]            at AutoMapper.MapperConfiguration.<>c__DisplayClass71_0.<FindMapper>b__0(IObjectMapper m)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0797996]            at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0798330]            at AutoMapper.MapperConfiguration.FindMapper(TypePair types)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0798636]            at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799019]            at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799358]            at System.Lazy`1.CreateValue()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799673]            at System.Lazy`1.LazyInitValue()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799955]            at System.Lazy`1.get_Value()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0800318]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0800682]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801012]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveTypeMap|17_5(TypePair types)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801337]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveMemberTypeMap|17_4(IMemberMap memberMap)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801637]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(IMemberMap pm)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801923]            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0802209]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0802568]            at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0802888]            at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0803198]            at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0803717]            at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0804420]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0804793]            at AutoMapper.MapperConfiguration.BuildExecutionPlan(MapRequest mapRequest)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0805147]            at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0805778]            at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0806238]            at System.Lazy`1.CreateValue()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0806747]            at System.Lazy`1.LazyInitValue()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0807189]            at System.Lazy`1.get_Value()
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0808023]            at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0808633]            at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
[2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0809433]         Automapper.Collection\src\AutoMapper.Collection.Tests\NotExistingTests.cs(39,0): at AutoMapper.Collection.NotExistingTests.Should_not_throw_exception_for_nonexisting_types()
```

**Comment by MaryadaPurshottam** [comment]
Any update on this. I'm still getting this error. 

> The exception is from a circular reference in the mapping that not `AutoMapper.Execution.TypeMapPlanBuilder` (in AM) will handle.
> 
> I have separated the test that will reproduce the error and it is a combination of how AM.Collection will check and create `Expressions` where the `Expression` is trying to find the real type. Exception have nothing to do with the AM.Collection.EFCore. The database object models often have references to both child and parent direction and that will cause the exception.
> 
> ```
> [2019-02-17 15:10:25 Error] [xUnit.net 00:00:01.0766059]     AutoMapper.Collection.NotExistingTests.Should_not_throw_exception_for_nonexisting_types [FAIL]
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0774607]       System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0782044]       Stack Trace:
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0788978]            at System.Lazy`1.CreateValue()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0789705]            at System.Lazy`1.LazyInitValue()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0790054]            at System.Lazy`1.get_Value()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0790394]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0790709]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0791232]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveTypeMap|17_5(TypePair types)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0791838]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveMemberTypeMap|17_4(IMemberMap memberMap)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0792289]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(IMemberMap pm)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0792624]            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0792929]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0793235]            at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0793492]            at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0793884]            at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0794398]            at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0794757]            at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0795150]            at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0795523]            at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0795916]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0796236]            at AutoMapper.MapperConfiguration.ResolveTypeMap(Type sourceType, Type destinationType)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0796808]         Automapper.Collection\src\AutoMapper.Collection\EquivalencyExpression\EquivalentExpressions.cs(63,0): at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0797351]         Automapper.Collection\src\AutoMapper.Collection\Mappers\EquivalentExpressionAddRemoveCollectionMapper.cs(76,0): at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0797671]            at AutoMapper.MapperConfiguration.<>c__DisplayClass71_0.<FindMapper>b__0(IObjectMapper m)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0797996]            at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0798330]            at AutoMapper.MapperConfiguration.FindMapper(TypePair types)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0798636]            at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799019]            at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799358]            at System.Lazy`1.CreateValue()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799673]            at System.Lazy`1.LazyInitValue()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0799955]            at System.Lazy`1.get_Value()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0800318]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0800682]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801012]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveTypeMap|17_5(TypePair types)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801337]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveMemberTypeMap|17_4(IMemberMap memberMap)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801637]            at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(IMemberMap pm)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0801923]            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0802209]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0802568]            at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0802888]            at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0803198]            at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0803717]            at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0804420]            at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0804793]            at AutoMapper.MapperConfiguration.BuildExecutionPlan(MapRequest mapRequest)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0805147]            at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0805778]            at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0806238]            at System.Lazy`1.CreateValue()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0806747]            at System.Lazy`1.LazyInitValue()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0807189]            at System.Lazy`1.get_Value()
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0808023]            at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0808633]            at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
> [2019-02-17 15:10:25 Informational] [xUnit.net 00:00:01.0809433]         Automapper.Collection\src\AutoMapper.Collection.Tests\NotExistingTests.cs(39,0): at AutoMapper.Collection.NotExistingTests.Should_not_throw_exception_for_nonexisting_types()
> ```
Any updates on this I'm still getting this error. Thanks

**Comment by Tasteful** [comment]
The issue is probably because of circular associations that you should avoid regarding to https://jimmybogard.com/automapper-usage-guidelines/

The issue is related to how AutoMapper is finding the correct mapping, see https://github.com/AutoMapper/AutoMapper/issues/2987 

A test to rebuild and use another method exists [here](https://github.com/AutoMapper/AutoMapper.Collection/pull/121) but it will not pass the tests so right now we are back in the beginning again.

**Comment by thomasrea0113** [comment]
I am also having this same issue
