### ISSUE TITLE
When DbContext dependency service,throw exception

### ISSUE THREAD

**Issue by ByZhouhang** [AutoMapper/AutoMapper.Collection.EFCore#60]
#### I did some audit information like CreateUserId   CreateTime  updateUserId   updateTime   in dbContext  before savechange, so i dependency a  service  get  httpcontext login user info  

``` C#
public IRaCISDBContext(DbContextOptions<IRaCISDBContext> options, IUserInfo userInfo) : base(options)
  {          
            _userInfo = userInfo;
  }
Config:
 automapper.AddCollectionMappers();

// add this code below  will throw exception if i dependency  IUserInfo 
automapper.UseEntityFrameworkCoreModel<IRaCISDBContext>(services)

Unable to resolve service for type 'IRaCIS.Core.Infra.EFCore.IUserInfo' while attempting to activate 'IRaCIS.Core.Infra.EFCore.IRaCISDBContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, 

```

#### when  not dependency IUserInfo .    try to  Execute :
 

``` C#
  _trialQCQuestionAnswerRepository.Persist(_mapper).InsertOrUpdate(qcQuestionAnswerCommands); 

   at lambda_method1059(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map(Object source, Object destination, Type sourceType, Type destinationType)
   at AutoMapper.Mapper.Map(Object source, Type sourceType, Type destinationType)
   at AutoMapper.EntityFrameworkCore.Persistence`1.GetEquivalenceExpression(Type type, Object from)
   at AutoMapper.EntityFrameworkCore.Persistence`1.InsertOrUpdate(Type type, Object from)
   at AutoMapper.EntityFrameworkCore.Persistence`1.InsertOrUpdate[TFrom](TFrom from)
   at IRaCIS.Core.Application.Image.QA.QCOperationService.AddOrUpdateQCQuestionAnswerList(QCQuestionAnswerCommand[] qcQuestionAnswerCommands, Guid trialId, Guid subjectVisitId, TrialQCProcess trialQCProcess, CurrentQC currentQCType, IServiceProvider serviceProvider) in D:\ZhiZhunProject\IRaCIS.Web.NetCore\IRaCIS.Core.Application\Service\QC\QCOperationService.cs:line 403
   at lambda_method723(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by Tasteful** [comment]
Have you try with configuration as in readme.md file where the serviceProvider is passed in instead of ServiceCollection?
